/*
        imagen: string (ruta de la imagen)
        sistemaOperativo: "Windows", "DOS", "Linux", "MacOS", "Chrome OS"
        marca: "HP", "Dell", "Lenovo", "Asus", "Acer", "Apple", "Samsung"
        tipo: "Notebook", "PC Armada", "Monitor"
        salary: number
        oferta: "Si"/"No"
        promocion: "Si"/"No"
        envioGratis: "Si"/"No"
*/

export const data = [
    // PCs de escritorio (PC Armada)
    {
        imagen: "Imagenes/Productos/CompuArmada/01_a.jpeg",
        imagenHover: "Imagenes/Productos/CompuArmada/01_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Dell",
        nombre: "Dell Inspiron 3880",
        tipo: "PC Armada",
        salary: 85000,
        oferta: "Si",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "480 GB",
        pantalla_tamanio: "27\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "No",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/02_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/02_b.jpeg",
        sistemaOperativo: "Linux",
        marca: "Lenovo",
        nombre: "Lenovo IdeaCentre 3",
        tipo: "PC Armada",
        salary: 78000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "1 TB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "Si",
        pantalla_led: "Si",
        memoria_ram: "4 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/03_a.webp",
        imagenHover: "/Imagenes/Productos/CompuArmada/03_b.webp",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "HP Pavilion TP01",
        tipo: "PC Armada",
        salary: 92000,
        oferta: "Si",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "256 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/04_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/04_b.jpeg",
        sistemaOperativo: "DOS",
        marca: "Asus",
        nombre: "Asus M32CD",
        tipo: "PC Armada",
        salary: 60000,
        oferta: "No",
        promocion: "No",
        envioGratis: "No",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "512 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "No",
        pantalla_led: "No",
        memoria_ram: "16 GB",
        gpu_dedicada: "SiNo",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/05_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/05_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Acer",
        nombre: "Acer Aspire TC",
        tipo: "PC Armada",
        salary: 75000,
        oferta: "Si",
        promocion: "No",
        envioGratis: "Si",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "512 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "Si",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/06_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/06_b.jpeg",
        sistemaOperativo: "Linux",
        marca: "Samsung",
        nombre: "Samsung Desktop",
        tipo: "PC Armada",
        salary: 82000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "512 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "Si",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/07_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/07_b.jpeg",
        sistemaOperativo: "MacOS",
        marca: "Apple",
        nombre: "Apple iMac",
        tipo: "PC Armada",
        salary: 150000,
        oferta: "No",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "960 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "Si",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/08_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/08_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Dell",
        nombre: "Dell G5",
        tipo: "PC Armada",
        salary: 89000,
        oferta: "Si",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "240 GB",
        pantalla_tamanio: "No",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/09_a.webp",
        imagenHover: "/Imagenes/Productos/CompuArmada/09_b.webp",
        sistemaOperativo: "Chrome OS",
        marca: "Acer",
        nombre: "Acer Chromebox",
        tipo: "PC Armada",
        salary: 68000,
        oferta: "Si",
        promocion: "Si",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "120 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/10_a.jpeg",
        imagenHover: "/Imagenes/Productos/CompuArmada/10_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "HP Omen 30L",
        tipo: "PC Armada",
        salary: 95000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "480 GB",
        pantalla_tamanio: "21.5\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/11_a.jpg",
        imagenHover: "/Imagenes/Productos/CompuArmada/11_b.jpg",
        sistemaOperativo: "Windows",
        marca: "Asus",
        nombre: "PC Gamer AMD Ryzen 5 5500 Ram 32Gb Ddr4 Nvme 2Tb Rtx 3050 8Gb Gddr6 Hdmi Dp Juegos Wifi Win10 Juegos Instalados",
        tipo: "PC Armada",
        salary: 1032550,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "2 TB",
        pantalla_tamanio: "No",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "32 GB",
        gpu_dedicada: "Si",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/12_a.webp",
        imagenHover: "/Imagenes/Productos/CompuArmada/12_b.webp",
        sistemaOperativo: "Windows",
        marca: "Asus",
        nombre: "Pc Gamer Amd Ryzen 7 5700g + 32gb + 1tb",
        tipo: "PC Armada",
        salary: 544544,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "1 TB",
        pantalla_tamanio: "No",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "32 GB",
        gpu_dedicada: "Si",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/13_a.webp",
        imagenHover: "/Imagenes/Productos/CompuArmada/13_b.webp",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "Pc Armada Gamer Amd Ryzen 7 5700g 32gb 960gb Ssd 32 Gb",
        tipo: "PC Armada",
        salary: 623434,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "960 GB",
        pantalla_tamanio: "No",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "32 GB",
        gpu_dedicada: "Si",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/14_a.jpg",
        imagenHover: "/Imagenes/Productos/CompuArmada/14_b.jpg",
        sistemaOperativo: "Windows",
        marca: "Asus",
        nombre: "PC Gamer INTEL Core i3 13100F - Rtx 3050 6Gb - RAM 16Gb - Ssd 1Tb - Monitor 24 - Wifi/Bt - Accesorios - Windows",
        tipo: "PC Armada",
        salary: 1340000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "1 TB",
        pantalla_tamanio: "24\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "Si",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/15_a.webp",
        imagenHover: "/Imagenes/Productos/CompuArmada/15_b.webp",
        sistemaOperativo: "Windows",
        marca: "Asus",
        nombre: "Pc Diseño Grafico Amd Ryzen 7 Ram 32gb Ssd 1tb Wifi",
        tipo: "PC Armada",
        salary: 787966,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "Si",
        usos: "Diseño",
        almacenamiento: "1 TB",
        pantalla_tamanio: "24\"",
        pantalla_tactil: "Si",
        pantalla_led: "Si",
        memoria_ram: "32 GB",
        gpu_dedicada: "Si",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/CompuArmada/16_a.webp",
        imagenHover: "/Imagenes/Productos/CompuArmada/16_b.webp",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "Pc Armada Intel Core I7 12700 32gb 1tb Fuente 650w Cert 80+ 32 Gb",
        tipo: "PC Armada",
        salary: 1039999,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Diseño",
        almacenamiento: "1 TB",
        pantalla_tamanio: "24\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "32 GB",
        gpu_dedicada: "Si",
        procesador: "Intel",
    },

    // Notebooks
    {
        imagen: "/Imagenes/Productos/Notebook/01_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/01_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Lenovo",
        nombre: "Lenovo IdeaPad 3",
        tipo: "Notebook",
        salary: 110000,
        oferta: "Si",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "14\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/02_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/02_b.jpeg",
        sistemaOperativo: "MacOS",
        marca: "Apple",
        nombre: "Apple MacBook Air",
        tipo: "Notebook",
        salary: 220000,
        oferta: "No",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/03_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/03_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "HP Pavilion 15",
        tipo: "Notebook",
        salary: 105000,
        oferta: "Si",
        promocion: "No",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/04_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/04_b.jpeg",
        sistemaOperativo: "Linux",
        marca: "Dell",
        nombre: "Dell Vostro 3400",
        tipo: "Notebook",
        salary: 98000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/05_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/05_b.jpeg",
        sistemaOperativo: "Chrome OS",
        marca: "Samsung",
        nombre: "Samsung Chromebook",
        tipo: "Notebook",
        salary: 87000,
        oferta: "Si",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/06_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/06_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Acer",
        nombre: "Acer Aspire 5",
        tipo: "Notebook",
        salary: 94000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "256 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/07_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/07_b.jpeg",
        sistemaOperativo: "Linux",
        marca: "Asus",
        nombre: "Asus VivoBook",
        tipo: "Notebook",
        salary: 102000,
        oferta: "Si",
        promocion: "Si",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/08_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/08_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Dell",
        nombre: "Dell Inspiron 15",
        tipo: "Notebook",
        salary: 97000,
        oferta: "No",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/09_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/09_b.jpeg",
        sistemaOperativo: "MacOS",
        marca: "Apple",
        nombre: "Apple MacBook Pro",
        tipo: "Notebook",
        salary: 250000,
        oferta: "Si",
        promocion: "No",
        envioGratis: "Si",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "240 GB",
        pantalla_tamanio: "14\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/10_a.jpeg",
        imagenHover: "/Imagenes/Productos/Notebook/10_b.jpeg",
        sistemaOperativo: "Windows",
        marca: "Lenovo",
        nombre: "Lenovo ThinkBook",
        tipo: "Notebook",
        salary: 89000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Oficina",
        almacenamiento: "512 GB",
        pantalla_tamanio: "14\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/11_a.webp",
        imagenHover: "/Imagenes/Productos/Notebook/11_b.webp",
        sistemaOperativo: "Windows",
        marca: "Acer",
        nombre: "Notebook Gamer Acer ALG Al15g-52 Intel Core I5-12450h 16gb 512gb Ssd 15.6 Full Hd Graficos Nvidia Geforce Rtx 2050 Windows 11 Teclado Retroiluminado Ingles Color Steel Gray",
        tipo: "Notebook",
        salary: 1199999,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/12_a.webp",
        imagenHover: "/Imagenes/Productos/Notebook/12_b.webp",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "Notebook Hp Gamer Victus 15-fb2026la AMD Ryzen 5 8gb Ram 512gb Ssd Rtx2050 4gb Windows 11 Home",
        tipo: "Notebook",
        salary: 1244499,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "Si",
        teclado_extra: "No",
        usos: "Juegos",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "8 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/13_a.webp",
        imagenHover: "/Imagenes/Productos/Notebook/13_b.webp",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "Notebook Hp 17 I7 Amd Radeon 16gb Ram 1tb Ssd Win Video 17.3",
        tipo: "Notebook",
        salary: 1099999,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Diseño",
        almacenamiento: "1 TB",
        pantalla_tamanio: "17.3\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "16 GB",
        gpu_dedicada: "No",
        procesador: "AMD",
    },
    {
        imagen: "/Imagenes/Productos/Notebook/14_a.webp",
        imagenHover: "/Imagenes/Productos/Notebook/14_b.webp",
        sistemaOperativo: "Windows",
        marca: "HP",
        nombre: "Laptop Hp 250 G10 15.6 Core I7-1355u Ram 32gb, Ssd M.2 512gb Color Gris Oscuro",
        tipo: "Notebook",
        salary: 1200000,
        oferta: "No",
        promocion: "Si",
        envioGratis: "No",
        gamer: "No",
        teclado_extra: "No",
        usos: "Diseño",
        almacenamiento: "512 GB",
        pantalla_tamanio: "15.6\"",
        pantalla_tactil: "No",
        pantalla_led: "Si",
        memoria_ram: "32 GB",
        gpu_dedicada: "No",
        procesador: "Intel",
    },
];